name: Lint GitHub Actions Workflows
on:
  push:
    paths:
      - .github/**

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # v4.0.0
      - name: "Check workflow files"
        uses: docker://docker.mirror.hashicorp.services/rhysd/actionlint:latest
        with:
          args: -color
