name: Test and Build

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod
      - name: Download go modules
        run: go mod download
      - name: Check Formatting
        run: |-
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "The following file(s) do not conform to go fmt:"
            echo "$files"
            exit 1
          fi
      - name: Vet code
        run: go vet ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20

  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.23' # named in go.mod
          - 'oldstable'
          - 'stable'
    env:
      TEST_RESULTS_PATH: '/tmp/test-results'
    steps:
      - name: Checkout Code
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install gotestsum
        uses: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f # v2.0.0
        with:
          gotestsum_version: 1.9.0

      - name: Create test directory
        run: mkdir -p "$TEST_RESULTS_PATH"
      - name: Run go tests
        run: |
          gotestsum --format=short-verbose --junitfile "$TEST_RESULTS_PATH/gotestsum-report.xml" -- -p 2 -cover -coverprofile=coverage.out ./...
      - name: Upload and save artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          path: ${{ env.TEST_RESULTS_PATH }}
          name: tests-linux-${{matrix.go-version}}
      - name: Upload coverage report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          path: coverage.out
          name: Coverage-report-${{matrix.go-version}}
      - name: Display coverage report
        run: go tool cover -func=coverage.out
