name: Test and Build

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: Download go modules
        run: go mod download
      - name: Check Formatting
        run: |-
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "The following file(s) do not conform to go fmt:"
            echo "$files"
            exit 1
          fi
      - name: Vet code
        run: go vet ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee

  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.23' # named in go.mod
          - 'oldstable'
          - 'stable'
    env:
      TEST_RESULTS_PATH: '/tmp/test-results'
    steps:
      - name: Checkout Code
        uses: actions/checkout@b9e0990d219a03df7633c93f6f005a8fecbcab22 # v4.0.0
      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install gotestsum
        uses: autero1/action-gotestsum@7263b9d73912eec65f46337689e59fac865c425f # v2.0.0
        with:
          gotestsum_version: 1.9.0

      - name: Create test directory
        run: mkdir -p "$TEST_RESULTS_PATH"
      - name: Run go tests
        run: |
          gotestsum --format=short-verbose --junitfile "$TEST_RESULTS_PATH/gotestsum-report.xml" -- -p 2 -cover -coverprofile=coverage.out ./...
      - name: Upload and save artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: ${{ env.TEST_RESULTS_PATH }}
          name: tests-linux-${{matrix.go-version}}
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          path: coverage.out
          name: Coverage-report-${{matrix.go-version}}
      - name: Display coverage report
        run: go tool cover -func=coverage.out
