name: Two-Stage PR Review Process

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, ready_for_review, converted_to_draft]
  pull_request_review:
    types: [submitted]

jobs:
  manage-pr-status:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: two-stage-pr-review
        uses: hashicorp/two-stage-pr-approval@chore/refactor-to-make-reusable-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
